DROP TABLE IF EXISTS TYPEPIECE;
CREATE TABLE TYPEPIECE (
	TYPEPIECE_id				TEXT				 		NOT NULL,
	TYPEPIECE_lib 				TEXT 						NOT NULL, 
	PRIMARY KEY (TYPEPIECE_id)
); 
INSERT INTO TYPEPIECE (TYPEPIECE_id,TYPEPIECE_lib) VALUES ('F','Facture');
INSERT INTO TYPEPIECE (TYPEPIECE_id,TYPEPIECE_lib) VALUES ('J','Justificatif règlement');
INSERT INTO TYPEPIECE (TYPEPIECE_id,TYPEPIECE_lib) VALUES ('E','Echéancier');
INSERT INTO TYPEPIECE (TYPEPIECE_id,TYPEPIECE_lib) VALUES ('VIR','Virement');
INSERT INTO TYPEPIECE (TYPEPIECE_id,TYPEPIECE_lib) VALUES ('P','Preuve');
INSERT INTO TYPEPIECE (TYPEPIECE_id,TYPEPIECE_lib) VALUES ('CHE','Chèque');
INSERT INTO TYPEPIECE (TYPEPIECE_id,TYPEPIECE_lib) VALUES ('C','Contrat');
INSERT INTO TYPEPIECE (TYPEPIECE_id,TYPEPIECE_lib) VALUES ('CGV','Conditions générales de vente');
INSERT INTO TYPEPIECE (TYPEPIECE_id,TYPEPIECE_lib) VALUES ('A','Article');
INSERT INTO TYPEPIECE (TYPEPIECE_id,TYPEPIECE_lib) VALUES ('Code','Code');
INSERT INTO TYPEPIECE (TYPEPIECE_id,TYPEPIECE_lib) VALUES ('B','Bon de commande');
INSERT INTO TYPEPIECE (TYPEPIECE_id,TYPEPIECE_lib) VALUES ('LCR','Lettre de change relève');
INSERT INTO TYPEPIECE (TYPEPIECE_id,TYPEPIECE_lib) VALUES ('AR','Courier avec AR');
INSERT INTO TYPEPIECE (TYPEPIECE_id,TYPEPIECE_lib) VALUES ('CS','Courier simple');
INSERT INTO TYPEPIECE (TYPEPIECE_id,TYPEPIECE_lib) VALUES ('FAX','Facsimilé');
INSERT INTO TYPEPIECE (TYPEPIECE_id,TYPEPIECE_lib) VALUES ('M','Mél');